---
language: java
jdk:
  - oraclejdk8

before_install:
  - rvm install 2.4.0
  - chmod +x gradlew

install:
  - ./gradlew --stacktrace --debug assemble

script:
  - cd scripts ; bundle install ; ./run_matches.rb
