---
language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - rvm install 2.4.0
  - chmod +x gradlew

install:
  - ./gradlew assemble

script:
  - cd scripts ; bundle install ; ./run_matches.rb
